/**
 * UI 字串預設值(zh-TW)。來源真相 + 永久 fallback。
 *
 * 採「扁平 dot-key」結構:t() 直接做 map 查找、深合併用 Object.assign、白名單驗證用 `key in`。
 * 管理頁的程式碼編輯器會整檔改寫 DATA_DIR/strings.json;此處為種子與後備。
 * 帶 {name} 的值由 t(key, {name}) 內插。
 *
 * 重要:這些值必須與 static/*.html 既有文字完全一致,未編輯的安裝套用後才不會有任何視覺變化。
 */
export const STRINGS_DEFAULT: Record<string, string> = {
  // ── common ──
  "common.logout": "登出",
  "common.role.admin": "管理員",
  "common.role.viewer": "訪客",
  "common.loading": "載入中…",
  "common.loadFail": "載入失敗",
  "common.cancel": "取消",
  "common.copy": "複製",
  "common.copied": "已複製",
  "common.close": "關閉",
  "common.segUnit": "段",

  // ── nav ──
  "nav.home": "首頁",
  "nav.browse": "瀏覽旅程",
  "nav.upload": "上傳",
  "nav.clips": "片段",
  "nav.admin": "管理",
  "nav.ops": "維運",
  "nav.account": "個人設定",
  "nav.menu": "選單",

  // ── 頁面標題(與 brand 以 titleTemplate 組合) ──
  "title.index": "",
  "title.browse": "瀏覽旅程",
  "title.account": "個人設定",
  "title.admin": "使用者管理",
  "title.trip": "旅程",
  "title.upload": "上傳影片",
  "title.clips": "匯出的片段",
  "title.login": "登入",
  "title.setup": "初始設定",
  "title.change": "設定新密碼",
  "title.ops": "維運與善後",

  // ── auth: login ──
  "auth.login.title": "歡迎回來",
  "auth.login.sub": "登入以瀏覽行車記錄",
  "auth.login.user": "帳號",
  "auth.login.userPlaceholder": "輸入帳號",
  "auth.login.password": "密碼",
  "auth.login.passwordPlaceholder": "輸入密碼",
  "auth.login.submit": "登入",
  "auth.login.submitting": "登入中…",
  "auth.login.errBad": "帳號或密碼不正確",
  "auth.login.errFail": "登入失敗，請稍後再試",

  // ── auth: setup ──
  "auth.setup.title": "建立管理員帳號",
  "auth.setup.sub": "這是此系統的初次設定，請建立一個管理員帳號",
  "auth.setup.user": "管理員帳號",
  "auth.setup.userPlaceholder": "例如：admin",
  "auth.setup.email": "Email",
  "auth.setup.emailHint": "（選填，用於 Gravatar 頭貼）",
  "auth.setup.emailPlaceholder": "example@example.com",
  "auth.setup.password": "密碼",
  "auth.setup.passwordPlaceholder": "至少 8 個字元",
  "auth.setup.confirm": "確認密碼",
  "auth.setup.confirmPlaceholder": "再次輸入密碼",
  "auth.setup.submit": "建立帳號",
  "auth.setup.submitting": "建立中…",
  "auth.setup.errMismatch": "兩次輸入的密碼不一致",
  "auth.setup.errShort": "密碼至少需要 8 個字元",
  "auth.setup.errExists": "系統已有帳號，請直接登入",
  "auth.setup.errFail": "建立失敗",

  // ── auth.change(首次強制改密碼頁 /change-password) ──
  "auth.change.title": "設定新密碼",
  "auth.change.sub": "為了帳號安全，首次登入請設定一組新密碼。",
  "auth.change.new": "新密碼",
  "auth.change.newPlaceholder": "至少 6 個字元",
  "auth.change.confirm": "確認新密碼",
  "auth.change.confirmPlaceholder": "再次輸入新密碼",
  "auth.change.submit": "設定並繼續",
  "auth.change.submitting": "設定中…",
  "auth.change.privacy": "密碼只保存加鹽後的單向雜湊，系統無法還原明文。",
  "auth.change.errMismatch": "兩次輸入的密碼不一致",
  "auth.change.errShort": "密碼至少需要 6 個字元",
  "auth.change.errFail": "設定失敗，請稍後再試",

  // ── index ──
  "index.eyebrow": "概覽",
  "index.stat.trips": "總旅程",
  "index.stat.tripsUnit": "趟",
  "index.stat.days": "騎乘天數",
  "index.stat.daysUnit": "天",
  "index.stat.hours": "總時數",
  "index.stat.hoursUnit": "小時",
  "index.stat.gforce": "最高 G-force",
  "index.recentTitle": "最近旅程",
  "index.latestTitle": "回味一下？",
  "index.calTitle": "騎乘日曆",
  "index.calLess": "少",
  "index.calMore": "多",
  "index.viewAll": "查看全部",
  "index.emptyTitle": "還沒有旅程紀錄",
  "index.emptyHint": "請管理員上傳行車記錄器的影片檔",

  // ── browse ──
  "browse.title": "瀏覽旅程",
  "browse.sub": "所有已整理的行車紀錄，依日期分類",
  "browse.dateHeading": "日期",
  "browse.empty": "暫無旅程紀錄",
  "browse.emptyTitle": "還沒有旅程紀錄",
  "browse.emptyHint": "請上傳行車記錄器影片",
  "browse.noTripThisDay": "這天沒有旅程",
  "browse.shake": "搖晃",
  "browse.ownerMine": "我的旅程",
  "browse.ownerOf": "{name} 的旅程",
  "browse.ownerPick": "選擇使用者",
  "browse.pickTitle": "要看誰的旅程?",
  "browse.pickHint": "以下使用者公開了他們的旅程,點選即可瀏覽;或上傳你自己的行車影片。",
  "browse.uploadCta": "上傳我的影片",

  // ── admin ──
  "admin.eyebrow": "管理員",
  "admin.title": "使用者管理",
  "admin.sub": "新增、刪除使用者，或更改密碼",
  "admin.addUser": "+ 新增使用者",
  "admin.storage.title": "資料碟使用情況",
  "admin.storage.tripsVideo": "旅程影片",
  "admin.storage.free": "可用空間",
  "admin.storage.db": "資料庫",
  "admin.storage.other": "其他資料",
  "admin.storage.available": "可用",
  "admin.storage.used": "已用",
  "admin.storage.totalPrefix": "共",
  "admin.activeUploads": "即時上傳狀況",
  "admin.activeCount": "{n} 個活躍 session",
  "admin.elapsedPrefix": "已過 ",
  "admin.idleTag": "（閒置 {s}s）",
  "admin.noUsers": "尚無使用者",
  "admin.self": "(自己)",
  "admin.changePwShort": "改密碼",
  "admin.updating": "更新中…",
  "admin.table.account": "帳號",
  "admin.table.role": "角色",
  "admin.table.actions": "操作",
  "admin.modal.newUser": "新增使用者",
  "admin.modal.account": "帳號",
  "admin.modal.email": "Email",
  "admin.modal.emailHint": "（選填，用於 Gravatar 頭貼）",
  "admin.modal.password": "密碼",
  "admin.modal.passwordPlaceholder": "至少 8 個字元",
  "admin.modal.requireChange": "首次登入時要求變更密碼",
  "admin.modal.requireChangeHint": "勾選後可不填密碼；使用者首次登入（密碼留空）後需自行設定新密碼。",
  "admin.modal.passwordOptional": "留空 = 首次登入時由使用者自行設定",
  "admin.modal.role": "角色",
  "admin.modal.roleViewer": "訪客（只能觀看）",
  "admin.modal.roleAdmin": "管理員（可上傳／管理）",
  "admin.modal.create": "建立",
  "admin.modal.changePassword": "更改密碼",
  "admin.modal.newPassword": "新密碼",
  "admin.modal.confirmPassword": "確認密碼",
  "admin.modal.confirmPlaceholder": "再次輸入",
  "admin.modal.updatePassword": "更新密碼",
  "admin.toast.created": "已建立使用者 {name}",
  "admin.toast.createFail": "建立失敗",
  "admin.toast.deleted": "已刪除 {name}",
  "admin.toast.deleteFail": "刪除失敗",
  "admin.toast.deleteConfirm": "確定要刪除使用者「{name}」？",
  "admin.toast.pwUpdated": "密碼已更新",
  "admin.toast.pwMismatch": "兩次輸入的密碼不一致",
  "admin.toast.updateFail": "更新失敗",
  "admin.status.processing": "處理中",
  "admin.status.uploading": "傳輸中",
  "admin.status.waiting": "等待上傳",
  "admin.updatedAt": "更新於 ",
  "admin.delete": "刪除",
  "admin.owner": "總管理員",
  "admin.roleAdmin": "管理員",
  "admin.roleViewer": "訪客",
  "admin.toast.roleChanged": "已更新 {name} 的角色",
  "admin.toast.roleChangeFail": "角色更新失敗",
  "admin.terminate": "中斷",
  "admin.terminateConfirm": "確定中斷「{name}」的上傳工作階段?已上傳的暫存檔會一併刪除。",
  "admin.terminated": "已中斷上傳工作階段",
  "admin.speedPrefix": "↑ ",
  "admin.files.title": "檔案總管",
  "admin.files.openBtn": "檢視檔案",
  "admin.files.sub": "所有旅程影片的實際存放位置,可下載或刪除。",
  "admin.files.pathLabel": "路徑",
  "admin.files.ownerLabel": "擁有者",
  "admin.files.download": "下載",
  "admin.files.downloadFront": "前鏡頭",
  "admin.files.downloadRear": "後鏡頭",
  "admin.files.delete": "刪除",
  "admin.files.deleteConfirm": "確定刪除此旅程及其影片檔?此操作無法復原。",
  "admin.files.deleted": "已刪除旅程",
  "admin.files.deleteFail": "刪除失敗",
  "admin.files.empty": "尚無旅程檔案",
  "admin.files.tripsUnit": "趟",

  // ── trip ──
  "trip.back": "← 瀏覽",
  "trip.camFront": "前鏡頭",
  "trip.camRear": "後鏡頭",
  "trip.switch": "⇄ 切換",
  "trip.noVideo": "無影片",
  "trip.switchMain": "點擊切換主畫面",
  "trip.playPause": "播放/暫停",
  "trip.prevFrame": "上一格",
  "trip.nextFrame": "下一格",
  "trip.speed": "播放速度",
  "trip.screenshot": "截圖存檔",
  "trip.fullscreen": "全螢幕",
  "trip.rateTitle": "串流下載速率",
  "trip.shortcuts":
    "滾輪縮放 · 拖曳平移 · 雙擊還原 · 空白鍵播放 · ←/→ 跳 5 秒 · ,/. 逐格 · S 截圖 · F 全螢幕",
  "trip.touchHints": "雙指縮放 · 單指拖曳平移 · 點兩下還原 · 點子母畫面切換鏡頭",
  "trip.notFound": "找不到此旅程",
  "trip.backLink": "← 返回",
  "trip.delete": "刪除",
  "trip.tripOrder": "第{order}趟",
  "trip.alertCrit": "偵測到強烈衝擊，最高 {g}g",
  "trip.alertWarn": "偵測到急煞／劇烈晃動，最高 {g}g",
  "trip.emerLock": "含 {n} 個 G-sensor 緊急鎖定片段",
  "trip.chipPeakG": "最高 G",
  "trip.chipDevice": "記錄器",
  "trip.chipEmer": "緊急片段",
  "trip.chipTime": "時間",
  "trip.chipDrive": "行駛",
  "trip.chipSeg": "片段",
  "trip.sameDay": "同天",
  "trip.camFrontShort": "前",
  "trip.camRearShort": "後",
  "trip.camSuffix": "鏡頭",
  "trip.screenshotSaved": "已截圖存檔",
  "trip.deleteConfirm": "確定要刪除此旅程及其影片？此操作無法復原。",
  "trip.deleted": "已刪除",
  "trip.deleteFail": "刪除失敗",
  "trip.edit": "剪輯",
  "trip.visibility": "可見性",
  "trip.visInherit": "跟隨帳號設定",
  "trip.visPublic": "公開",
  "trip.visPrivate": "不公開",
  "trip.visSaved": "已更新此旅程的可見性",
  "trip.visFail": "更新可見性失敗",
  "trip.trim.title": "裁剪影片",
  "trip.trim.hint": "設定要保留的起點與終點,前後鏡頭會一起裁剪(精確重編碼,原始檔保留可還原)。",
  "trip.trim.start": "起點",
  "trip.trim.end": "終點",
  "trip.trim.setCurrent": "設為目前畫面",
  "trip.trim.rangeLen": "保留長度",
  "trip.trim.apply": "套用裁剪",
  "trip.trim.processing": "裁剪中…",
  "trip.trim.doneReload": "裁剪完成,重新載入…",
  "trip.trim.restore": "還原原始影片",
  "trip.trim.confirmApply": "確定裁剪?會以精確重編碼產生新影片(原始檔會保留,可還原)。",
  "trip.trim.confirmRestore": "還原成裁剪前的原始影片?",
  "trip.trim.restored": "已還原原始影片",
  "trip.trim.cancelled": "已取消裁剪",
  "trip.trim.fail": "裁剪失敗",
  "trip.trim.badRange": "請設定有效的起點與終點(終點需大於起點)",
  "trip.trimmedBadge": "已裁剪",
  "trip.trim.sectionTitle": "整趟裁剪(破壞性)",
  "trip.trim.sectionHint": "把整趟旅程永久縮短成上方選取的區間(前後鏡頭一起,原始檔保留可還原)。多數情況請改用上面的「匯出片段」。",
  "trip.clip.selectTitle": "選取片段",
  "trip.clip.selectHint": "拖曳時間軸上的入點/出點把手,或按 I / O 把入點、出點設在目前畫面。",
  "trip.clip.in": "入點",
  "trip.clip.out": "出點",
  "trip.clip.setIn": "設為入點 (I)",
  "trip.clip.setOut": "設為出點 (O)",
  "trip.clip.length": "長度",
  "trip.clip.preview": "▶ 預覽選取",
  "trip.clip.previewStop": "■ 停止預覽",
  "trip.clip.title": "匯出片段",
  "trip.clip.hint": "把選取的區間另存成一支獨立影片(原旅程不受影響),可重複下載或刪除。",
  "trip.clip.layout": "版面",
  "trip.clip.layoutFront": "前鏡頭",
  "trip.clip.layoutRear": "後鏡頭",
  "trip.clip.layoutPip": "子母畫面",
  "trip.clip.quality": "畫質",
  "trip.clip.qualityPrecise": "精確",
  "trip.clip.qualityFast": "快速",
  "trip.clip.qualityFastHint": "快速為無損直接複製,不重編碼,速度最快;切點落在關鍵幀,頭尾會多帶數秒畫面(檢舉佐證建議用此模式)。",
  "trip.clip.qualityPipHint": "子母畫面需重編碼,僅精確模式。",
  "trip.clip.label": "標題(選填)",
  "trip.clip.labelPlaceholder": "例:超車、路口事故…",
  "trip.clip.export": "匯出片段",
  "trip.clip.cpuNote": "這裡為 CPU 硬解，請耐心等候",
  "trip.clip.exporting": "匯出中…",
  "trip.clip.done": "片段匯出完成",
  "trip.clip.fail": "匯出失敗",
  "trip.clip.cancelled": "已取消匯出",
  "trip.clip.badRange": "請先在時間軸上選取有效區間(至少 1 秒)",
  "trip.clip.tooMany": "目前有其他片段正在匯出,請稍候再試",
  "trip.clip.listTitle": "已匯出的片段",
  "trip.clip.empty": "尚無匯出的片段。",
  "trip.clip.download": "下載",
  "trip.clip.delete": "刪除",
  "trip.clip.deleteConfirm": "確定刪除這個片段?",
  "trip.clip.deleted": "已刪除片段",
  "trip.clip.deleteFail": "刪除失敗",
  "trip.clip.gotoPage": "→ 前往片段頁查看",
  "trip.clip.processed": "已處理",
  "trip.clip.sourceRange": "來源",
  "trip.clip.reportCta": "⚑ 產生檢舉資料",
  "trip.clip.reportHint": "檢舉用途建議:前鏡頭＋快速(無損)——受理單位要求原始畫面,無損模式不重新壓縮。",
  "trip.clipConnLost": "連線中斷,匯出仍在背景進行,請稍後重新整理片段頁查看結果",
  "trip.trimConnLost": "連線中斷,裁剪仍在背景進行,請稍後重新整理查看結果",
  "trip.copyLink": "複製連結(含目前時間)",
  "trip.linkCopied": "已複製連結,開啟後會從此時間點播放",
  "trip.share.button": "快速分享（免登入）",
  "trip.share.title": "快速分享這趟旅程",
  "trip.share.lead": "收件人不必登入；連結只會開啟這趟旅程的影片，不會看到其他旅程或私人備註。分享者可隨時撤銷。",
  "trip.share.expiry": "連結有效期限",
  "trip.share.oneDay": "1 天",
  "trip.share.sevenDays": "7 天（建議）",
  "trip.share.thirtyDays": "30 天",
  "trip.share.create": "建立分享連結",
  "trip.share.ready": "分享連結，直接傳給對方即可",
  "trip.share.once": "連結會加密保管，關閉或換裝置後仍可再次複製。",
  "trip.share.linkLabel": "分享連結，直接傳給對方即可",
  "trip.share.savedNote": "連結會加密保管，關閉或換裝置後仍可再次複製。",
  "trip.share.manage": "分享紀錄",
  "trip.share.empty": "尚未建立分享連結",
  "trip.share.activeCount": "{n} 個有效連結",
  "trip.share.createdAt": "建立於 {time}",
  "trip.share.active": "有效",
  "trip.share.inactive": "已失效",
  "trip.share.rowMeta": "有效至 {expiry} · 已開啟 {count} 次",
  "trip.share.never": "不限期限",
  "trip.share.revoke": "撤銷",
  "trip.share.copyAgain": "再次複製分享連結",
  "trip.share.retrieveFail": "取得分享連結失敗",
  "trip.share.rotate": "重新產生",
  "trip.share.rotateConfirm": "原本的分享連結將立即失效，確定要重新產生？",
  "trip.share.rotated": "分享連結已重新產生並複製",
  "trip.share.rotateFail": "重新產生分享連結失敗",
  "trip.share.revokeConfirm": "確定撤銷這個分享連結？對方將無法再開啟。",
  "trip.share.created": "分享連結已建立並複製",
  "trip.share.createFail": "建立分享失敗",
  "trip.share.copied": "已複製分享連結",
  "trip.share.revoked": "分享連結已撤銷",
  "trip.share.revokeFail": "撤銷分享失敗",
  "trip.resumed": "已從上次觀看位置續播({t})",

  // ── clips 片段頁(/clips) ──
  "clips.pageTitle": "匯出的片段",
  "clips.subtitle": "從各趟旅程剪出、另存的獨立片段。原旅程不受影響。",
  "clips.count": "共 {n} 個片段",
  "clips.empty": "還沒有匯出任何片段",
  "clips.emptyHint": "打開任一趟旅程,按「剪輯 → 匯出片段」,結果就會出現在這裡。",
  "clips.play": "▶ 播放",
  "clips.download": "下載",
  "clips.delete": "刪除",
  "clips.deleteConfirm": "確定刪除這個片段?此動作無法復原。",
  "clips.deleted": "已刪除片段",
  "clips.deleteFail": "刪除失敗",
  "clips.source": "來源",
  "clips.loadFail": "載入片段失敗",
  "clips.browseCta": "去瀏覽旅程",
  "clips.report": "檢舉",
  "clips.reportedBadge": "已檢舉",
  "clips.report.title": "產生檢舉資料",
  "clips.report.notice":
    "提醒:檢舉採實名制;違規行為終了起 7 日內有效;請在檢舉系統上傳影片「原始檔」,勿貼連結。",
  "clips.report.timeLabel": "違規時間",
  "clips.report.timeHint": "依旅程起始時間＋片段位置自動換算;送出前請與畫面上的時間戳核對。",
  "clips.report.plate": "車牌號碼",
  "clips.report.platePh": "如 ABC-1234",
  "clips.report.location": "違規地點",
  "clips.report.locationPh": "路名/路口,如 中山路與民族路口",
  "clips.report.violation": "違規事實",
  "clips.report.violationPh": "選擇或自行輸入,如 闖紅燈",
  "clips.report.desc": "補充描述(選填)",
  "clips.report.descPh": "行向、車道、經過…",
  "clips.report.templateText":
    "違規時間:{time}\n違規地點:{location}\n車牌號碼:{plate}\n違規事實:{violation}\n{desc}佐證影片:見附件(擷取行車記錄器,含車機時間戳,未經剪接變造)。",
  "clips.report.copyText": "複製檢舉文字",
  "clips.report.copied": "已複製,貼到檢舉系統的「違規事實描述」欄位",
  "clips.report.download": "下載片段(檢舉附件)",
  "clips.report.goSystem": "前往檢舉系統",
  "clips.report.goSystemUnset": "尚未設定所在縣市的檢舉系統網址(管理員可在「管理 → 檢舉輔助」設定),可先用下方常用入口。",
  "clips.report.commonLinks": "常用檢舉入口",
  "clips.report.markReported": "標記為已檢舉",
  "clips.report.unmarkReported": "取消已檢舉標記",
  "clips.report.saved": "已儲存檢舉資料",
  "clips.report.saveFail": "儲存失敗",
  "trip.secUnit": "秒",
  "trip.minUnit": "分 ",
  "trip.hourUnit": "小時 ",
  "trip.noteTitle": "備註",
  "trip.noteEmpty": "尚無備註",
  "trip.noteAdd": "新增備註",
  "trip.noteEdit": "編輯",
  "trip.noteSave": "儲存",
  "trip.noteCancel": "取消",
  "trip.notePlaceholder": "為這趟旅程加上備註…",
  "trip.noteSaved": "備註已儲存",
  "trip.noteSaveFail": "儲存失敗",

  // ── upload ──
  "upload.eyebrow": "上傳影片",
  "upload.title": "上傳行車記錄",
  "upload.intro":
    "建立上傳工作階段後，在工作階段內確認或更換來源記錄器，再把記憶卡檔案拖進瀏覽器（或用 SFTP），完成後按「確認並處理」。",
  "upload.howTitle": "怎麼上傳?",
  "upload.step1": "按「建立上傳工作階段」，再於工作階段內確認或更換這批影片的來源記錄器。",
  "upload.step2":
    "可直接拖入 MiVue FILE/EMER…F/R.mp4（含可用的 .NMEA）、Polaroid MS279WG …A/B.TS，或已整理的 YYYY-MM-DD/ 旅程資料夾；也可展開進階 SFTP 連線資訊。",
  "upload.step3": "傳完按該工作階段的「確認並處理」。系統會核對所選記錄器格式；實際閒置期限顯示在工作階段上。",
  "upload.createBtn": "建立上傳工作階段",
  "upload.creating": "建立中…",
  "upload.emptyList": "目前沒有進行中的上傳工作階段。",
  "upload.preparing": "準備中…",
  "upload.sessionLabel": "上傳工作階段",
  "upload.rowServer": "伺服器",
  "upload.rowUser": "使用者",
  "upload.rowPassword": "密碼",
  "upload.rowAuthUrl": "一鍵連線網址",
  "upload.rowFilezillaCmd": "FileZilla 指令",
  "upload.rowFilezillaCmdMac": "FileZilla 指令 (mac)",
  "upload.uploaded": "已上傳",
  "upload.filesUnit": "個檔案",
  "upload.downloadFz": "下載 FileZilla 站台",
  "upload.gap": "間隔",
  "upload.gapUnit": "分",
  "upload.confirmBtn": "確認並處理",
  "upload.created": "已建立上傳工作階段",
  "upload.createFail": "建立失敗",
  "upload.cancelConfirm": "確定取消?資料夾與已上傳的檔案都會被刪除。",
  "upload.cancelled": "已取消工作階段",
  "upload.cancelFail": "取消失敗",
  "upload.received": "已接收 {n} 個檔案",
  "upload.skipped": ",略過 {n} 個",
  "upload.startProcessing": ",開始處理…",
  "upload.uploading": "上傳中…",
  "upload.speedPrefix": "↑ ",
  "upload.statusProcessing": "處理中",
  "upload.statusWaiting": "等待上傳",
  "upload.done": "完成!",
  "upload.doneToast": "旅程處理完成!",
  "upload.errStage": "發生錯誤",
  "upload.errConn": "× 連線中斷",
  "upload.fzDownloaded": "已下載;FileZilla → 檔案 → 匯入,即可一鍵連線",
  "upload.expiresSuffix": "後到期",
  "upload.confirmFail": "確認處理失敗",
  "upload.dropTitle": "把檔案拖到這裡,或",
  "upload.pickFiles": "選擇檔案",
  "upload.pickFolder": "選擇資料夾",
  "upload.dropHint": "支援 MiVue F/R.mp4 + .NMEA、Polaroid MS279WG A/B.TS，或 YYYY-MM-DD/ 已整理旅程；請保留原始檔名。",
  "upload.queueTitle": "上傳佇列",
  "upload.qUploading": "上傳中",
  "upload.qWaiting": "等待中",
  "upload.qDone": "完成",
  "upload.qError": "失敗",
  "upload.qRejected": "格式不符,略過",
  "upload.qRetry": "重試",
  "upload.qRetryAll": "重試失敗檔案",
  "upload.qHide": "收起清單",
  "upload.qShow": "檢視清單",
  "upload.qOverall": "整體進度",
  "upload.qDoneToast": "檔案全部上傳完成,可按「確認並處理」",
  "upload.qSomeFail": "有 {n} 個檔案上傳失敗,可按「重試失敗檔案」",
  "upload.uploadingBlockConfirm": "仍有檔案上傳中,請等待完成後再確認",
  "upload.leaveUploading": "檔案還在上傳,離開會中斷傳輸",
  "upload.sftpAdvanced": "進階:SFTP 連線資訊(FileZilla / WinSCP / 指令列)",
  "upload.filesOnServer": "已上傳到伺服器的檔案",
  "upload.fileDelete": "刪除",
  "upload.fileDeleted": "已刪除檔案",
  "upload.errConnRetry": "連線中斷,嘗試重新連線…",
  "upload.noLimit": "不限時",
  "upload.qConnFail": "連線失敗",
  "upload.doneWithIssues": "處理完成,但有 {n} 筆問題待處理(素材已隔離保留,管理員可到「維運」重試)",
  "upload.rejectedList": "略過的檔案:{names}",

  // ── ops / 維運善後 ──
  "ops.eyebrow": "管理員",
  "ops.title": "維運與善後",
  "ops.sub": "追查處理失敗、執行修復措施、檢視資料庫",
  "ops.incidents.head": "事件與善後",
  "ops.incidents.filterOpen": "待處理",
  "ops.incidents.filterAll": "全部",
  "ops.incidents.empty": "目前沒有事件,一切正常",
  "ops.incidents.colTime": "時間",
  "ops.incidents.colKind": "類型",
  "ops.incidents.colTitle": "事件",
  "ops.incidents.colStatus": "狀態",
  "ops.kind.merge_failed": "合併失敗",
  "ops.kind.trip_skipped": "旅程略過",
  "ops.kind.processing_error": "處理例外",
  "ops.status.open": "待處理",
  "ops.status.resolved": "已解決",
  "ops.status.dismissed": "已忽略",
  "ops.detail.title": "事件詳情",
  "ops.detail.reason": "原因",
  "ops.detail.context": "技術內容",
  "ops.detail.quarantine": "隔離素材",
  "ops.detail.quarantineYes": "已保留,可重試",
  "ops.detail.quarantineNo": "無(無法重試,需重新上傳)",
  "ops.action.retry": "重新合併",
  "ops.action.retryTolerant": "容錯重合",
  "ops.action.discard": "刪除素材",
  "ops.action.resolve": "標記已解決",
  "ops.action.dismiss": "忽略",
  "ops.action.delete": "刪除事件",
  "ops.retry.running": "重試進行中…",
  "ops.retry.started": "已開始重試",
  "ops.retry.connLost": "連線中斷,重試仍在背景進行,請稍後重新整理查看結果",
  "ops.confirm.discard": "確定刪除此事件的隔離素材?刪除後就無法再重試。",
  "ops.confirm.delete": "確定刪除此事件記錄?",
  "ops.toast.resolved": "已標記",
  "ops.toast.deleted": "已刪除",
  "ops.toast.fail": "操作失敗",
  "ops.health.head": "旅程健康檢查",
  "ops.health.scan": "掃描旅程",
  "ops.health.scanning": "掃描中…",
  "ops.health.ok": "所有旅程影片正常",
  "ops.health.result": "檢查 {checked} 趟,發現 {n} 趟有問題",
  "ops.health.issueNoVideo": "前後鏡頭皆無影片",
  "ops.health.issuePartial": "部分鏡頭影片為空",
  "ops.health.deleteTrip": "刪除該趟",
  "ops.health.rebuild": "從磁碟重建",
  "ops.db.head": "資料庫檢視(唯讀)",
  "ops.db.pickTable": "選擇資料表",
  "ops.db.rows": "筆",
  "ops.db.prev": "上一頁",
  "ops.db.next": "下一頁",
  "ops.db.redactNote": "敏感欄位(密碼、token)已遮蔽",
  "ops.tools.head": "維運工具",
  "ops.tools.rebuild": "從磁碟重建資料庫",
  "ops.tools.rebuilding": "重建中…",
  "ops.tools.rebuilt": "重建完成,匯入 {n} 趟",
  "ops.tools.retention": "隔離素材保留天數",

  // ── 個人設定頁(account.html) ──
  "account.eyebrow": "我的帳號",
  "account.title": "個人設定",
  "account.sub": "管理你的帳號、看片偏好與介面外觀。",
  "account.section.account": "帳號",
  "account.username": "帳號",
  "account.usernameHint": "登入帳號,無法更改。",
  "account.currentPassword": "目前密碼",
  "account.newPassword": "新密碼",
  "account.confirmPassword": "確認新密碼",
  "account.changePassword": "更新密碼",
  "account.pwHint": "更新後,其他已登入的裝置會被登出。",
  "account.pwPrivacy": "密碼只保存加鹽後的單向雜湊，系統無法還原明文。",
  "account.pwOk": "密碼已更新",
  "account.pwMismatch": "兩次輸入的新密碼不一致",
  "account.section.email": "Email(頭像)",
  "account.displayName": "顯示名稱",
  "account.displayNameHint": "各處介面(頁首、瀏覽選單、管理列表)會優先顯示此名稱;留空則顯示帳號。",
  "account.email": "Email",
  "account.emailHint": "用於顯示 Gravatar 頭像;留空則用文字頭像。",
  "account.profileOk": "已儲存",
  "account.section.viewing": "看片偏好",
  "account.camera": "預設主鏡頭",
  "account.cameraGlobal": "跟隨全域設定",
  "account.front": "前鏡頭",
  "account.rear": "後鏡頭",
  "account.speed": "預設播放速度",
  "account.speedDefault": "預設(1×)",
  "account.section.theme": "介面主題",
  "account.theme": "主題",
  "account.themeAuto": "自動(跟隨系統)",
  "account.themeLight": "淺色",
  "account.themeDark": "深色",
  "account.section.device": "使用的行車記錄器",
  "account.deviceNote": "安裝備註",
  "account.deviceHint": "可管理多台記錄器；每次上傳會保存當時的型號與備註，不受日後修改影響。",
  "account.save": "儲存",
  "account.section.visibility": "旅程可見性",
  "account.publicTrips": "公開我的旅程",
  "account.publicTripsHint": "開啟後,其他登入的使用者可在「瀏覽旅程」的選單看到並觀看你的旅程;關閉則僅你本人與管理員可見。",
  "account.visibilitySaved": "已更新旅程可見性",
};
